# PUT   http://localhost:3000/api/library/comics/1 HTTP/1.1
# Content-Type: application/json

# {
#       "title": "Nacho Book",
#       "author": "Luis Soto",
#       "year": 2044,
#       "genre": "Superhero",
#       "illustrator": "Tim Sale",
#       "available": false
# }


# PUT   http://localhost:3000/api/library/magazines/1 HTTP/1.1
# Content-Type: application/json

# {
#       "id": 0,
#       "title": "Nacho Book",
#       "genre": "Superhero",
#       "issue": "arroz",
#       "available": false
# }