PATCH    http://localhost:3000/api/library/comics/1 HTTP/1.1
Content-Type: application/json

{
      "title": "Nacho Book",
      "author": "Luis Soto",
}


PATCH   http://localhost:3000/api/library/magazines/1 HTTP/1.1
Content-Type: application/json

{
      "genre": "Superhero",
      "issue": "arroz",
}