PATCH  http://localhost:3000/api/library/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "SpiderMan",
    "author": "Jeph Loeb",
    "year": 2002,
    "genre": "Superhero",
    "illustrator": "Tim Sale",
    "available": true
}
